package checker_test

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/oasdiff/oasdiff/checker"
	"github.com/oasdiff/oasdiff/checker/metaschema"
)

const coverageDocPath = "../docs/COVERAGE.md"

// TestCoverageDoc verifies that docs/COVERAGE.md matches the rule registry
// and the metaschema cube. Regenerate with: make coverage-doc
func TestCoverageDoc(t *testing.T) {
	want := coverageDoc()
	if os.Getenv("UPDATE_COVERAGE_DOC") != "" {
		if err := os.WriteFile(coverageDocPath, []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(coverageDocPath)
	if err != nil {
		t.Fatalf("%v; generate the file with: make coverage-doc", err)
	}
	// a Windows checkout may convert the file to CRLF
	if strings.ReplaceAll(string(got), "\r\n", "\n") != want {
		t.Error("docs/COVERAGE.md is out of date with the rule registry; regenerate with: make coverage-doc")
	}
}

func coverageDoc() string {
	cube := metaschema.Edits()

	type ruleRef struct {
		id    string
		level checker.Level
	}
	type claimant struct {
		claim metaschema.Claim
		ruleRef
	}
	var claims []claimant
	for _, rule := range checker.GetAllRules() {
		for _, loc := range rule.Locations {
			claim, err := metaschema.ParseClaim(loc)
			if err != nil {
				continue // TestRuleLocations reports it
			}
			claims = append(claims, claimant{claim, ruleRef{rule.Id, rule.Level}})
		}
	}

	covered := map[metaschema.Edit][]ruleRef{}
	var wire, wireCovered int
	var holes []metaschema.Edit
	for _, edit := range cube {
		for _, c := range claims {
			if c.claim.Matches(edit) {
				covered[edit] = append(covered[edit], c.ruleRef)
			}
		}
		if edit.Annotation || edit.Extension {
			continue
		}
		wire++
		if len(covered[edit]) > 0 {
			wireCovered++
		} else {
			holes = append(holes, edit)
		}
	}

	// attribute each uncovered wire-relevant edit to its first matching waiver
	waiverEdits := make([]int, len(coverageWaivers))
	for _, edit := range holes {
		for i, w := range coverageWaivers {
			if waiverMatchesDoc(w.Pattern, edit) {
				waiverEdits[i]++
				break
			}
		}
	}

	var b strings.Builder
	b.WriteString(`# Coverage of the OpenAPI Edit Space

<!-- Generated by "make coverage-doc"; do not edit by hand. -->

This page maps the changelog checks onto the full edit space of an OpenAPI
document. The edit space is derived mechanically from the OpenAPI object
model: every field location (a dotted path, with ` + "`*`" + ` standing for any map key
or list index) paired with the syntactic edits applicable there (add, remove,
set, unset, change, increase, decrease). Schema locations are folded: a edit
like ` + "`paths.*.*.requestBody.content.*.schema.maxLength`" + ` stands for that
keyword at any nesting depth inside the request body schema.

Two guarantees are enforced by tests in the checker package:

- Every location a check claims exists in the object model, so this map
  cannot drift from the specification as the parser evolves.
- Every wire-relevant edit (one whose edit can change which payloads are
  valid) is either covered by at least one check or listed in the second
  table below with a reason. A new field in the object model, or a removed
  check, fails the build until this map accounts for it.

Checks for the same edit differ by preconditions on the document (for
example, whether the removed endpoint was deprecated); severity levels are
listed per check.

`)

	fmt.Fprintf(&b, "## Summary\n\n")
	fmt.Fprintf(&b, "- %d edits in the edit space, %d of them wire-relevant\n", len(cube), wire)
	fmt.Fprintf(&b, "- %d wire-relevant edits covered by checks\n", wireCovered)
	fmt.Fprintf(&b, "- %d wire-relevant edits without checks, all accounted for below\n\n", len(holes))

	b.WriteString("## Checked edits\n")
	groups := map[string][]metaschema.Edit{}
	for edit := range covered {
		groups[context(edit.Location)] = append(groups[context(edit.Location)], edit)
	}
	groupNames := make([]string, 0, len(groups))
	for g := range groups {
		groupNames = append(groupNames, g)
	}
	sort.Strings(groupNames)
	for _, g := range groupNames {
		edits := groups[g]
		sort.Slice(edits, func(i, j int) bool {
			if edits[i].Location != edits[j].Location {
				return edits[i].Location < edits[j].Location
			}
			return edits[i].Action < edits[j].Action
		})
		fmt.Fprintf(&b, "\n### `%s`\n\n", g)
		b.WriteString("| Location | Action | Checks |\n|---|---|---|\n")
		for _, edit := range edits {
			refs := covered[edit]
			sort.Slice(refs, func(i, j int) bool { return refs[i].id < refs[j].id })
			names := make([]string, len(refs))
			for i, r := range refs {
				names[i] = fmt.Sprintf("`%s` (%s)", r.id, r.level.String())
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", edit.Location, edit.Action, strings.Join(names, ", "))
		}
	}

	b.WriteString(`
## Edits without checks

Each remaining wire-relevant edit matches one of the entries below. Counts
attribute every edit to its first matching entry.

| Pattern | Cells | Reason |
|---|---|---|
`)
	for i, w := range coverageWaivers {
		fmt.Fprintf(&b, "| `%s` | %d | %s |\n", w.Pattern, waiverEdits[i], w.Reason)
	}
	return b.String()
}

// waiverMatchesDoc is waiverMatches without the testing.T plumbing; patterns
// are validated by TestRuleCoverage.
func waiverMatchesDoc(pattern string, edit metaschema.Edit) bool {
	if !strings.Contains(pattern, ":") {
		return metaschema.MatchLocation(pattern, edit.Location)
	}
	claim, err := metaschema.ParseClaim(pattern)
	if err != nil {
		return false
	}
	return claim.Matches(edit)
}
